# Generated by Django 5.2.6 on 2025-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('banco', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('nome_arquivo', models.CharField(max_length=255)),
            ],
        ),
    ]
