# Generated by Django 5.2.6 on 2025-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_fluxoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoarquivo',
            name='convenio',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='emailOuContato',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='observação',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='recebido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='situacao',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='tipo',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='fluxoarquivo',
            name='tipo_op',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
