# Generated by Django 5.2.6 on 2025-10-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_fluxoarquivo_convenio_fluxoarquivo_emailoucontato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxoarquivo',
            name='hora_encerramento',
            field=models.TimeField(null=True),
        ),
    ]
