# Generated by Django 5.2.6 on 2025-10-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_fluxoarquivo_hora_encerramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='convenio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='emailOuContato',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='hora_encerramento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='observação',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='recebido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='situacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='tipo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='fluxoarquivo',
            name='tipo_op',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
